"""
SQLAlchemy models — compatible with both PostgreSQL (PostGIS) and SQLite.
IT22629180
"""
import os
from sqlalchemy import Column, Integer, String, Float, Text, DateTime, Boolean
from sqlalchemy.orm import declarative_base
from sqlalchemy.sql import func

Base = declarative_base()

# Detect if we're using SQLite (no geoalchemy2 support)
_DB_URL = os.environ.get("SQLALCHEMY_DATABASE_URI", "")
_USE_POSTGIS = "postgresql" in _DB_URL or "postgres" in _DB_URL

try:
    from geoalchemy2 import Geometry
    _HAVE_GEO = True
except ImportError:
    _HAVE_GEO = False


def _geo_col(geometry_type: str):
    """Return a PostGIS Geometry column or None if using SQLite."""
    if _HAVE_GEO and _USE_POSTGIS:
        return Column(Geometry(geometry_type=geometry_type, srid=4326), nullable=True)
    return Column(Text, nullable=True)  # Store as WKT text in SQLite


class Report(Base):
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    source = Column(String, index=True)          # "reddit", "youtube", "web", etc.
    url = Column(String, nullable=True)          # original source URL (used for deduplication)
    title = Column(String, nullable=True)        # article/post title
    content = Column(Text, nullable=False)       # main text content

    # NLP & ML derived fields
    sentiment_score = Column(Float, nullable=True)   # -1.0 to 1.0
    is_scam = Column(Boolean, default=False)
    scam_type = Column(String, nullable=True)        # "tuk_tuk", "gem_shop", "theft", etc.
    risk_level = Column(Integer, default=1)          # 1=low, 2=moderate, 3=high

    # Geospatial data
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    location_point = _geo_col("POINT")
    location_name = Column(String, nullable=True)

    # Metadata
    demographic_target = Column(String, nullable=True)  # "solo_female", "family", etc.
    source_weight = Column(Float, default=0.35)          # 0.0-1.0 credibility score (see source_weights.py)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class RiskZone(Base):
    """Generated by DBSCAN clustering from Reports."""
    __tablename__ = "risk_zones"

    id = Column(Integer, primary_key=True, index=True)
    cluster_id = Column(Integer, unique=True, index=True)
    zone_polygon = _geo_col("POLYGON")
    center_point = _geo_col("POINT")
    risk_score = Column(Float, nullable=False)
    primary_scam_type = Column(String, nullable=True)
    report_count = Column(Integer, default=0)
    last_updated = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
